class_based_crud/class_based_crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

class_based_crud/myapp/urls.py
from django.urls import path
from myapp import views
urlpatterns = [
    path('', views.Home.as_view()),
    path('add/', views.AddRecord.as_view()),
    path('update/<int:pk>/', views.UpdateRecord.as_view()),
    path('delete/<int:pk>/', views.DeleteRecord.as_view()),
]

class_based_crud/myapp/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    eno = models.IntegerField()
    ename = models.CharField(max_length=20)
    esal = models.FloatField()
    eemail = models.EmailField()
    eaddress = models.TextField()

class_based_crud/myapp/forms.py
from django import forms
from .models import Employee
class Employeeform(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

class_based_crud/myapp/views.py
from django.shortcuts import render
from .models import Employee
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .forms import Employeeform
# Create your views here.
class Home(ListView):
    model = Employee
    template_name = 'myapp/home.html'
class AddRecord(CreateView):
    model = Employee
    form_class = Employeeform
    template_name = 'myapp/add.html'
    success_url = '/'

class UpdateRecord(UpdateView):
    model = Employee
    form_class = Employeeform
    pk_url_kwarg = 'pk'
    template_name = 'myapp/update.html'
    success_url = '/'

class DeleteRecord(DeleteView):
    model = Employee
    pk_url_kwarg = 'pk'
    template_name = 'myapp/delete.html'
    success_url = '/'

class_based_crud/templates/myapp/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
{% csrf_token %}
    {% for field in form.visible_fields %}

    {{field.label}}<br>{{field}}<br>
    {% endfor %}
    <input type="submit" value="submit"><br>
    <a href = '/'>Show Records </a>
</form>
</body>
</html>

class_based_crud/templates/myapp/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method = "post">
    {% csrf_token %}
    <p>Are you sure you want to delete Record ?</p>
    <input type = "submit" value = "delete">
</form>

</body>
</html>

class_based_crud/templates/myapp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

</head>
<body>
<table class="table-condensed" align="center" >
    <thead>
    <th>Eno</th>
    <th>Ename</th>
    <th>Esal</th>
    <th>Email</th>
    <th>Address</th>
    <th>operation1</th>
    <th>operation2</th>
    </thead>
    {% for i in employee_list %}
    <tr>
        <td>{{i.eno}}</td>
        <td>{{i.ename}}</td>
        <td>{{i.esal}}</td>
        <td>{{i.eemail}}</td>
        <td>{{i.eaddress}}</td>
        <td><a href="/update/{{i.id}}">Update</a> </td>
        <td><a href="/delete/{{i.id}}">Delete</a> </td>
    </tr>
    {% endfor %}
</table>
<a href="/add" align = "center">Add New Record</a>
</body>
</html>

class_based_crud/templates/myapp/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method = "post">
    {% csrf_token %}
    {% for field in form.visible_fields %}
    {{field.label}}<br>
    {{field}}<br>
    {% endfor %}
    <button type="submit" class = "btn-btn-success">Submit</button>
    <a href="/">Home</a>
</form>

</body>
</html>